### ISSUE TITLE
git 계정

### ISSUE THREAD

**Issue by kkally** [LiJell/Final-pjt#18]
git 계정이슈 반복적으로 발생

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"       

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address

**Comment by kkally** [comment]
git config --global user.email "[you@example.com](mailto:you@example.com)"
git config --global user.name "Your Name"

1차적으로는 성공이었지만 반복적으로 발생한다

**Comment by LiJell** [comment]
자동으로 이메일 주소를 인식하지 못하는 문제

**Comment by LiJell** [comment]
git bash 관리자 권한으로 실행 후 설정하면 해결될듯 함.

**Comment by LiJell** [comment]
해결된듯함
