### ISSUE TITLE
service page issue

### ISSUE THREAD

**Issue by LiJell** [LiJell/Final-pjt#87]
- [x] 스타일별 사진 추가
- [x] 스타일 옵션 순서 변경 및 디즈니 삭제
- [x] 강아지 사진만 된다는 문구 추가
- [x] 파일 확장자 제한
- [x] 용량 제한 
- [x] 결과 이미지 크게 나오게 변경

**Comment by dodo-Riley** [comment]
용량제한은 추후 단순히 컴퓨팅 파워만 올리면 해결 가능한 부분으로 경고 문구만 추가

**Comment by dodo-Riley** [comment]
service 및 result 페이지 번역, 쿼리스트링을 이용해 해당 언어의 결과 페이지가 출력되도록 수정

**Comment by dodo-Riley** [comment]
결과이미지 너비를 10rem에서 20rem으로 수정

**Comment by dodo-Riley** [comment]
모든 스타일 예시 이미지 추가, 디즈니 스타일 제거

**Comment by dodo-Riley** [comment]
파일 확장자를 jpg와 png만 입력 예상 파일로 인식하도록 수정 및 다른 파일은 불가능하다는 문구 추가
